### ISSUE TITLE
Encoding to CNF for any BNN

### ISSUE THREAD

**Issue by arnabsharma91** [teobaluta/NPAQ#10]
Hi!
I have read your paper and the found the idea of NPAQ very interesting. I would like to know whether is it possible to use your approach to encode any BNN to CNF formula or is it hard coded only for MNIST and UCI Adult dataset? If the encoding can be done for any BNN how to do so?

Thanks in advance!

**Comment by teobaluta** [comment]
Hi Arnab,

Thank you for your interest in our tool! At the moment, we only support models trained in PyTorch for MNIST and UCI Adult dataset. You can take a look at how we write the parameters of these models in [1] and write your model's parameters following the same procedure. Then you can use the C++ encoder we have in `mlp2cnf` directly on these parameters.

[1] https://github.com/teobaluta/NPAQ/blob/master/npaq/bnn_dataset.py#L483

**Comment by arnabsharma91** [comment]
Hi Teodora!

Thank you so much for your reply. That was really helpful. I will definitely try that.
