### ISSUE TITLE
Input features' CNF-encoding and mapping variables to features

### ISSUE THREAD

**Issue by allrtaken** [teobaluta/NPAQ#17]
Hi,

I was wondering how multi-valued input features are encoded into the Boolean domain for different datasets (one-hot, log-encoding etc.). How can I map the variables in the formulas to the respective features? In particular, if I have a satisfying assignment for a formula, how I can I obtain the instance in the original feature space (possibly discretized), that it corresponds to and vice-versa?

Thanks in advance!

**Comment by teobaluta** [comment]
Hi there,

Sorry for the late reply. For the MNIST dataset, we just flatten the input image into a vector. For the UCI dataset, we follow a log-encoding and add constraints for what values cannot be taken. Please see below.

Constraints specific to UCI Dataset

- workclass
    - 8 values, 3 bits => no need to add constraints, all inputs are valid inputs
- education
    - 16 values, 4 bits => no need for constraints
- marital
    - 7 values, 3 bits => add constraint 111 not VALID input
    - ['Married-civ-spouse', 'Divorced', 'Never-married', 'Separated',   'Widowed', 'Married-spouse-absent', 'Married-AF-spouse']
- occupation
    - 14 values, 4 bits => add constraint for last 2 values 110, 111
- relationship
    - 6 values, 3 bits => add constraint for last 2 values 110, 111
- race
    - 5 values, 3 bits => add constraints for last 3 values
- country
    - 41 values, 6 bits => add constraints

Thanks,
Teo
